---
title: "git_01"
author: "Diego Martinez"
date: "7/10/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 


A BOAT beneath a sunny sky,     
Lingering onward dreamily     
In an evening of July    
Children three that nestle near,    
Eager eye and willing ear,     


<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse

Something there is that doesn't love a wall,      
That sends the frozen-ground-swell under it,      
And spills the upper boulders in the sun;    
And makes gaps even two can pass abreast.     
The work of hunters is another thing:    



<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse


"The sun was shining on the sea,       
      Shining with all his might:       
He did his very best to make         
      The billows smooth and bright —      
And this was odd, because it was     
      The middle of the night.      

The moon was shining sulkily,    
      Because she thought the sun    
Had got no business to be there    
      After the day was done —    
"It's very rude of him," she said,     
      "To come and spoil the fun."       



<!--Put the first two verses of The Walrus and the Carpenter here!-->


## Last Verse

I’m a riddle in nine syllables,      
An elephant, a ponderous house,     
A melon strolling on two tendrils.    
O red fruit, ivory, fine timbers!     
This loaf’s big with its yeasty rising.    
Money’s new-minted in this fat purse.     
I’m a means, a stage, a cow in calf.    
I’ve eaten a bag of green apples,     
Boarded the train there’s no getting off.    


